SELECT "Creating new apex_host table" AS "";

CREATE TABLE IF NOT EXISTS apex_host (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  create_timestamp TIMESTAMP NOT NULL,
  name VARCHAR(45) NOT NULL,
  host VARCHAR(45) NOT NULL,
  sql_user VARCHAR(45) NOT NULL,
  sql_pass VARCHAR(45) NOT NULL,
  allocation FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE INDEX uq_name (name ASC))
ENGINE = InnoDB;


DELIMITER $$

DROP TRIGGER IF EXISTS apex_host_BEFORE_INSERT $$
CREATE DEFINER = CURRENT_USER TRIGGER apex_host_BEFORE_INSERT BEFORE INSERT ON apex_host FOR EACH ROW
BEGIN
SET NEW.create_timestamp = NOW();
END$$

DELIMITER ;
